/*

 EXPORT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\GB\aclean113\tiles_jeu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define iintro03Width 32
#define iintro03Height 32
#define iintro03Bank 0

extern unsigned char iintro03[];

/* End of EXPORT.H */
