/*

 WATERMAP5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : waterCustom3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define waterMap5Width 64
#define waterMap5Height 64
#define waterMap5Bank 0

extern unsigned char waterMap5[];

/* End of WATERMAP5.H */
