/*

 WATERMAP6A.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : waterCustom4.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define waterMapg1Width 64
#define waterMapg1Height 64
#define waterMapg1Bank 0

extern unsigned char waterMapg1[];

/* End of WATERMAP6A.H */
