/*

 WATERMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : C:\GB\acleangood1\assets\waterCustom.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define wtaerMap2Width 64
#define wtaerMap2Height 64
#define wtaerMap2Bank 0

extern unsigned char wtaerMap2[];

/* End of WATERMAP2.H */
