/*

 WATERMAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : C:\GB\acleangood1\assets\waterCustom.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define waterMap3Width 64
#define waterMap3Height 64
#define waterMap3Bank 0

extern unsigned char waterMap3[];

/* End of WATERMAP3.H */
